title: Stream Toys
description: >-
  Stream toys for OBS, flapper clock, countdown and world clock
theme: minima
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Flapper-1.1.6
  - jquery-3.7.1.min.js
  - jquery.transform-0.9.3.min.js
